project_id = "zadsuqxcchpnegcynflb"

[functions.email-intake]
verify_jwt = false

[functions.mintsoft-sync]
verify_jwt = false

[functions.fetch-queued-price-checks]
verify_jwt = false

[functions.update-price-check-results]
verify_jwt = false

[functions.mintsoft-test-order-count]
verify_jwt = false

[functions.mintsoft-order-snapshot]
verify_jwt = false

[functions.mintsoft-statuses]
verify_jwt = false

[functions.mintsoft-backorder-age-snapshot]
verify_jwt = false

[functions.send-ops-weekly-report]
verify_jwt = false