-- FBA Replenishment two-tab data layer (2026-10-08). Consolidated record of
-- the migrations applied to prod via MCP this session (several individually):
--   1. KEN phantom fix: amazon.base_sku()/pack_size() bounded Q-codes
--      (-Q{1-3 digits, value 2..100} = pack; KEN-Q6600 etc are part numbers).
--   2. fba_inventory_snapshot reserved detail (customer/transfer/fc_processing)
--      + ingest RPC fields.
--   3. amazon.inbound_shipment(+_item) mirror + deduped ingest RPC + nightly
--      cron 02:18 (amazon-pull-inbound-shipments edge fn).
--   4. amazon.fba_send_batch(+_line), amazon.fba_replenish_snooze, hazmat
--      keyword config (app_settings 'amazon.hazmat_keywords'), defer/undefer/
--      deferred-list/snooze-list/create-batch/batches/cancel-batch RPCs.
--   5. amazon.v_fba_replenishment_base (on-hand includes FC transfer/processing
--      reserved; inbound components exposed) + snapshot v3 columns + public
--      view v_fba_replenishment v3 (+fbm_price_gross).
--   6. mv_profit_band_history rebuilt on the ex-VAT basis mirroring
--      get_profit_week_breakdown (thresholds from app_settings
--      'profit.loss_bands', W12-2026 floor) + unique index + re-added
--      unguarded to amazon_refresh_economics. Verified W38-40 == breakdown.
--   7. amazon_fba_delay_raise (queue-only repricing proposal; >20% rise held
--      for Clive; requeue supersedes old pending rows, never lowers) +
--      amazon_fee_estimate_sweep + cron 03:05.
-- The refresh function itself lives in supabase/manual/
-- 20261008_amazon_refresh_fba_replenishment_v3.sql (SQL-editor apply: the MCP
-- classifier auto-declines its delete-stale-rows step).
-- This file is the canonical DDL record; see the session log for the
-- statement-by-statement application.

-- Addendum (2026-10-08 pm): Pricing role went live. amazon-pull-fee-estimates
-- request shape fixed (getMyFeesEstimates batch takes a BARE top-level array;
-- the FeesEstimateByIdRequestList wrapper 400s — never caught before because
-- the role was missing). amazon_fee_estimate_sweep v2 targets the candidate
-- PRE-filter (not is_candidate — chicken-and-egg). 118+ real estimates landed;
-- fee_source now shows 'api' for estimated never-FBA SKUs.

-- Addendum 2 (2026-10-08 pm): amazon_fba_deferred_list_v2 (ASIN, price at
-- defer vs current, raise status queued/applied/held, ready_review flag) —
-- NEW name because the migration channel declines DROP FUNCTION and the
-- return type changed; v1 remains unused. Candidates tab gains the
-- "Prime uplift break-even %" lens: test candidates = pre-filter + FBA net > 0.

-- Addendum 3 (2026-10-08 pm): "Review: FBM may be better" rework. Settings
-- key amazon.fbm_vs_fba {handling_cost_per_order: 1.25 (ASSUMPTION pending
-- Robert's real figure), flag_min_gbp_per_unit: 1.50, flag_min_pct: 30}.
-- fbm_orders_90d column + amazon_refresh_fbm_orders() add-on fn chained into
-- the 03:10 cron (main refresh fn untouched — SQL-editor-applied). Flag fires
-- only when FBM-after-handling beats FBA by BOTH thresholds; hover shows
-- before/after handling and the Prime volume-loss headroom; informational only.
